version: '3.8'
services:
  api:
    build: .
    ports: ["5001:5001"]
    volumes: ["./app:/app"]

  grafana:
    image: grafana/grafana-oss
    ports: ["3000:3000"]
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - ./app/sensor-data.csv:/var/lib/grafana/data/sensor-data.csv:ro
  